### ISSUE TITLE
documention side request authentication

### ISSUE THREAD

**Issue by mictadlo** [shamblett/wilt#15]
Visiting http://oscf.org.uk/dart/api/wilt/ I got:

    Unauthorized

    This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by shamblett** [comment]
Hi,

Yes, sorry my fault, the is not here anymore, the API is generated
automatically when you publish a package these days. the site is
http://www.dartdocs.org/, specifically Wilt is here
http://www.dartdocs.org/documentation/wilt/3.1.0/index.html#wilt

I'll update the docs/pub for the next release.



On 17 January 2015 at 09:52, Michał T. Lorenc <notifications@github.com>
wrote:

> Visiting http://oscf.org.uk/dart/api/wilt/ I got:
>
> Unauthorized
>
> This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shamblett/wilt/issues/15>.
>



-- 
"Talk is cheap. Show me the code."
- Linus Torvalds

Steve Hamblett

**Comment by mictadlo** [comment]
No worries. At github under contact is also the outdated link.

**Comment by shamblett** [comment]
Fixed, version 3.2.0
