### ISSUE TITLE
Bulk insert which yielded 1000 a documents or 16MB of data

### ISSUE THREAD

**Issue by mictadlo** [shamblett/wilt#16]
Any plans to implement a bulk insert which yield for example 1000 documents or 16MB of data and then insert all of them to couchdb similar like PyMongo work.

PyMongo will iterate your generator until it has yielded 1000 a documents or 16MB of data, then pause the generator while it inserts the batch into MongoDB. Once the batch is inserted PyMongo resumes your generator to create the next batch, and continues until all documents are inserted. Then insert() returns a list of inserted document ids.

Initial support for generators was added to PyMongo in [this commit](https://github.com/mongodb/mongo-python-driver/commit/ec6b7bc06e549fa661b60abbb5c841fe7180541b) and we've maintained support for document generators ever since.

**Comment by shamblett** [comment]
Hi,

At the mo Wilt just tracks the couchdb API, however we can of course add
any higher level API's(like this) we wish. If you think this would be a
good addition then I'll look at this for the next release, thanks for the
heads up.

On 17 January 2015 at 10:08, Michał T. Lorenc <notifications@github.com>
wrote:

> Any plans to implement a bulk insert which yield for example 1000
> documents or 16MB of data and then insert all of them to couchdb similar
> like PyMongo work.
>
> PyMongo will iterate your generator until it has yielded 1000 a documents
> or 16MB of data, then pause the generator while it inserts the batch into
> MongoDB. Once the batch is inserted PyMongo resumes your generator to
> create the next batch, and continues until all documents are inserted. Then
> insert() returns a list of inserted document ids.
>
> Initial support for generators was added to PyMongo in this commit
> <https://github.com/mongodb/mongo-python-driver/commit/ec6b7bc06e549fa661b60abbb5c841fe7180541b>
> and we've maintained support for document generators ever since.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shamblett/wilt/issues/16>.
>



-- 
"Talk is cheap. Show me the code."
- Linus Torvalds

Steve Hamblett

**Comment by mictadlo** [comment]
It would be awesome and useful. [Here](http://java.dzone.com/articles/mongodb-facts-over-80000) is a PyMongo benchmark.
