### ISSUE TITLE
Something wrong with error processing when DB is not available

### ISSUE THREAD

**Issue by VladimirCores** [shamblett/wilt#34]
Consider this question and try to stop DB:
https://stackoverflow.com/questions/71951737/httpclient-request-can-not-catch-the-error-in-flutter

**Comment by VladimirCores** [comment]
@shamblett could you please take a look on the issue, it is important?

**Comment by shamblett** [comment]
Im on holiday at the mo, back in UK 25th so Ill look at this early next week. In the meantime could you attach a log showing the failure.

**Comment by VladimirCores** [comment]
There is no log, the response on error is not thrown when DB is down, request never fulfilled.

**Comment by shamblett** [comment]
Ok, which request is never fulfilled?

 Have you created a client and logged in then done some operations then took the db down or have you done somethong else?

I need to know exactly what you are doing.

Maybe post your test code.

**Comment by VladimirCores** [comment]
Just stop couchdb instance and try to connect, there will be no errors or anything.

**Comment by shamblett** [comment]
When you say 'just stop couchdb instance' do you mean stop the machine it is running on, or leave the machine running and stop the couchdb instance on it.
